### ISSUE TITLE
Pre-release version of Kotlin

### ISSUE THREAD

**Issue by Vivecstel** [skydoves/Orbital#11]
**Please complete the following information:**
- Library Version [e.g. v0.20]
- Affected Device(s) [Samsung Galaxy A53 with Android 12.0]
 
**Describe the Bug:**

Getting this error:
is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
And i have kotlin 1.7.10, compose 1.3.0-alpha03 and compose compiler 1.3.0

**Expected Behavior:**

Should be able to build the project without issues when adding the orbital library.

**Comment by skydoves** [comment]
Hi @Vivecstel,
a new version `0.2.1` was released. Could you try to build your project with this version? Thanks!

**Comment by Vivecstel** [comment]
Hmm I am still getting the same error with 0.2.1. It seems weird because I have the same versions as Orbital. Didn't have this issue with your rest compose libraries (landscapist, orchestra).

**Comment by skydoves** [comment]
Hey, thank you for checking this. What about `0.2.2-SNAPSHOT`?

**Comment by Vivecstel** [comment]
It worked with the snapshot release @skydoves .
Thanks.
